/**
 * Privacy-aware PNG: aggregates and names only — no meal photos or full text.
 */
import { aggregateWeek, wellnessScore } from "./weekly.js";
import { weekSummaryExtras } from "./analytics.js";

function wrapLines(ctx, text, maxWidth) {
  const words = text.split(/\s+/);
  const lines = [];
  let cur = "";
  for (const w of words) {
    const test = cur ? `${cur} ${w}` : w;
    if (ctx.measureText(test).width <= maxWidth) {
      cur = test;
    } else {
      if (cur) lines.push(cur);
      cur = w;
    }
  }
  if (cur) lines.push(cur);
  return lines;
}

/**
 * @returns {Promise<Blob>}
 */
export function renderWeeklySummaryPng(state, weekStart, weekLabel) {
  const agg = aggregateWeek(state.meals, weekStart);
  const ws = wellnessScore(agg.health, agg.rated);
  const extra = weekSummaryExtras(agg);
  const u1 = state.users.find((x) => x.id === "u1");
  const u2 = state.users.find((x) => x.id === "u2");
  const n1 = u1?.name || "Person 1";
  const n2 = u2?.name || "Person 2";

  const W = 720;
  const H = 920;
  const canvas = document.createElement("canvas");
  canvas.width = W;
  canvas.height = H;
  const ctx = canvas.getContext("2d");
  if (!ctx) return Promise.reject(new Error("Canvas not supported"));

  ctx.fillStyle = "#1c1917";
  ctx.fillRect(0, 0, W, H);

  ctx.fillStyle = "#e7e5e4";
  ctx.font = "600 28px system-ui, sans-serif";
  ctx.fillText("आहार Tracker — weekly summary", 40, 52);

  ctx.font = "400 16px system-ui, sans-serif";
  ctx.fillStyle = "#a8a29e";
  ctx.fillText(weekLabel, 40, 82);
  ctx.fillStyle = "#78716c";
  ctx.font = "12px system-ui, sans-serif";
  ctx.fillText("Totals only — no meal photos or descriptions in this image.", 40, 102);

  let y = 140;
  ctx.fillStyle = "#d6d3d1";
  ctx.font = "18px system-ui, sans-serif";

  const lines = [
    `Household meals logged: ${agg.totalMeals}`,
    `Total kcal tracked: ${agg.caloriesSum || "—"}`,
    `Average kcal / meal: ${agg.avgCalories ?? "—"}`,
    `Wellness score (rated meals): ${ws ?? "—"}`,
    `Best day (by kcal): ${extra.bestDayLabel}${extra.bestDayKcal != null ? ` (~${extra.bestDayKcal} kcal)` : ""}`,
    `Most common category: ${extra.topCategory} (${extra.topCategoryCount} meal(s))`,
  ];

  for (const line of lines) {
    ctx.fillText(line, 40, y);
    y += 32;
  }

  y += 20;
  ctx.font = "16px system-ui, sans-serif";
  ctx.fillStyle = "#a8a29e";
  ctx.fillText("People (names only)", 40, y);
  y += 28;
  ctx.fillStyle = "#d6d3d1";
  const a1 = aggregateWeek(state.meals, weekStart, "u1");
  const a2 = aggregateWeek(state.meals, weekStart, "u2");
  ctx.fillText(`${n1}: ${a1.totalMeals} meals, ${a1.caloriesSum || "—"} kcal, score ${wellnessScore(a1.health, a1.rated) ?? "—"}`, 40, y);
  y += 28;
  ctx.fillText(`${n2}: ${a2.totalMeals} meals, ${a2.caloriesSum || "—"} kcal, score ${wellnessScore(a2.health, a2.rated) ?? "—"}`, 40, y);

  y += 40;
  ctx.fillStyle = "#57534e";
  ctx.font = "13px system-ui, sans-serif";
  const disclaimer =
    "Generated by your browser. Does not include meal titles, notes, or images. Share carefully.";
  for (const line of wrapLines(ctx, disclaimer, W - 80)) {
    ctx.fillText(line, 40, y);
    y += 20;
  }

  return new Promise((resolve, reject) => {
    canvas.toBlob(
      (blob) => {
        if (blob) resolve(blob);
        else reject(new Error("Could not create image."));
      },
      "image/png",
      0.92
    );
  });
}
